#!/usr/bin/env bash
# Auto-generated one-click install script for: cartoon-xiaban
# Generated by publish-skill — https://skill.vyibc.com/install-publish-skill.sh
set -euo pipefail

SKILL_NAME="cartoon-xiaban"
ZIP_URL="https://skill.vyibc.com/cartoon-xiaban/release/cartoon-xiaban-20260907112558.zip"
ZIP_SHA256="23e12dd029748bdaab9d54a9f146ad0c505feefb177e518c7e9e357fb321ad0f"

# ── 工具选择 ──────────────────────────────────────────────
TARGET="${1:-}"
if [[ -z "$TARGET" ]]; then
  echo "🛠  选择安装 ${SKILL_NAME} 到哪个 AI 工具："
  echo "  1) Codex        (~/.codex/skills/)"
  echo "  2) Cursor       (~/.cursor/skills/)"
  echo "  3) Claude       (~/.claude/skills/)"
  echo "  4) Gemini       (~/.gemini/skills/)"
  echo "  5) Antigravity  (~/.gemini/antigravity/skills/)"
  echo "  6) Copilot      (~/.copilot/skills/)"
  echo "  7) OpenClaw     (~/.openclaw/workspace/skills/)"
  echo "  8) Agents       (~/.agents/skills/)"
  echo "  9) Hermes       (~/.hermes/skills/devops/)"
  echo " 10) 全部安装"
  read -rp "请输入编号 [1-10]: " CHOICE
  case "$CHOICE" in
    1) TARGET="codex"       ;;
    2) TARGET="cursor"      ;;
    3) TARGET="claude"      ;;
    4) TARGET="gemini"      ;;
    5) TARGET="antigravity" ;;
    6) TARGET="copilot"     ;;
    7) TARGET="openclaw"    ;;
    8) TARGET="agents"      ;;
    9) TARGET="hermes"      ;;
   10) TARGET="all"         ;;
    *) echo "❌ 无效选项"; exit 1 ;;
  esac
fi

case "$TARGET" in
  codex)       DIRS=("$HOME/.codex/skills")                          ;;
  cursor)      DIRS=("$HOME/.cursor/skills")                         ;;
  claude)      DIRS=("$HOME/.claude/skills")  ;;
  gemini)      DIRS=("$HOME/.gemini/skills")                         ;;
  antigravity) DIRS=("$HOME/.gemini/antigravity/skills")             ;;
  copilot)     DIRS=("$HOME/.copilot/skills")                 ;;
  openclaw)    DIRS=("$HOME/.openclaw/workspace/skills")      ;;
  agents)      DIRS=("$HOME/.agents/skills")                  ;;
  hermes)      DIRS=("$HOME/.hermes/skills/devops")           ;;
  all)
    DIRS=(
      "$HOME/.codex/skills"
      "$HOME/.cursor/skills"
      "$HOME/.claude/skills"
      "$HOME/.gemini/skills"
      "$HOME/.gemini/antigravity/skills"
      "$HOME/.copilot/skills"
      "$HOME/.openclaw/workspace/skills"
      "$HOME/.hermes/skills/devops"
    ) ;;
  *) echo "❌ 不支持的 target: $TARGET"; exit 1 ;;
esac

# Codex user discovery follows ~/.agents/skills; keep a single canonical copy.
CODEX_LINK="$HOME/.agents/skills/${SKILL_NAME}"
CODEX_DEST="$HOME/.codex/skills/${SKILL_NAME}"
if [[ "$TARGET" == "codex" || "$TARGET" == "all" ]]; then
  if [[ -e "$CODEX_LINK" || -L "$CODEX_LINK" ]]; then
    if [[ ! -L "$CODEX_LINK" || "$(readlink "$CODEX_LINK")" != "$CODEX_DEST" ]]; then
      echo "❌ 已有独立发现目录，请先保留并处理：$CODEX_LINK" >&2
      exit 1
    fi
  fi
fi

echo ""
echo "🚀 安装 ${SKILL_NAME} ..."
echo ""

# ── 下载 zip ──────────────────────────────────────────────
TMPWORK=$(mktemp -d /tmp/install-skill-XXXXXX)
trap 'rm -rf "$TMPWORK"' EXIT

echo "   下载 ${ZIP_URL} ..."
curl -fsSL "${ZIP_URL}" -o "${TMPWORK}/skill.zip"

if command -v sha256sum &>/dev/null; then
  ACTUAL_SHA256=$(sha256sum "${TMPWORK}/skill.zip" | awk '{print $1}')
elif command -v shasum &>/dev/null; then
  ACTUAL_SHA256=$(shasum -a 256 "${TMPWORK}/skill.zip" | awk '{print $1}')
elif command -v python3 &>/dev/null; then
  ACTUAL_SHA256=$(python3 -c 'import hashlib,sys; print(hashlib.sha256(open(sys.argv[1], "rb").read()).hexdigest())' "${TMPWORK}/skill.zip")
else
  echo "❌ 需要 sha256sum、shasum 或 python3 来验证安装包" >&2
  exit 1
fi
if [[ "${ACTUAL_SHA256}" != "${ZIP_SHA256}" ]]; then
  echo "❌ 安装包 SHA-256 校验失败" >&2
  exit 1
fi
echo "   🔐 SHA-256 校验通过"

# ── 解压到临时目录（优先 unzip，回退到 python3）────────────
mkdir -p "${TMPWORK}/extracted"
if command -v unzip &>/dev/null; then
  unzip -q "${TMPWORK}/skill.zip" -d "${TMPWORK}/extracted"
elif command -v python3 &>/dev/null; then
  python3 -m zipfile -e "${TMPWORK}/skill.zip" "${TMPWORK}/extracted"
elif command -v python &>/dev/null; then
  python -m zipfile -e "${TMPWORK}/skill.zip" "${TMPWORK}/extracted"
else
  echo "❌ 需要 unzip 或 python3 来解压，请先安装其中一个" >&2
  exit 1
fi

# 解压后的目录就是 <skill-name>/
EXTRACTED_DIR="${TMPWORK}/extracted/${SKILL_NAME}"
if [[ ! -d "$EXTRACTED_DIR" ]]; then
  # 兼容：如果 zip 里只有一个目录，用它
  EXTRACTED_DIR=$(find "${TMPWORK}/extracted" -mindepth 1 -maxdepth 1 -type d | head -1)
fi

# ── 复制到各目标目录 ──────────────────────────────────────
for BASE_DIR in "${DIRS[@]}"; do
  DEST="${BASE_DIR}/${SKILL_NAME}"
  mkdir -p "$BASE_DIR"
  if [[ -e "$DEST" || -L "$DEST" ]]; then
    BACKUP_ROOT="${BASE_DIR}/.backups"
    mkdir -p "$BACKUP_ROOT"
    BACKUP="${BACKUP_ROOT}/${SKILL_NAME}-$(date +%Y%m%d-%H%M%S)-$$"
    [[ ! -e "$BACKUP" && ! -L "$BACKUP" ]] || { echo "Backup path already exists" >&2; exit 1; }
    mv "$DEST" "$BACKUP"
    echo "  ↪ 原版本已备份：$BACKUP"
  fi
  cp -r "$EXTRACTED_DIR" "$DEST"
  find "$DEST/scripts" -name "*.sh" -exec chmod +x {} \; 2>/dev/null || true
  echo "  ✅ → $DEST"
done

if [[ "$TARGET" == "codex" || "$TARGET" == "all" ]]; then
  mkdir -p "$HOME/.agents/skills"
  if [[ ! -L "$CODEX_LINK" ]]; then
    ln -s "$CODEX_DEST" "$CODEX_LINK"
  fi
  echo "  ✅ Codex 发现链接 → $CODEX_LINK"
fi

echo ""
echo "✅ 安装完成！下一轮可使用 ${SKILL_NAME}；若未刷新，请重启 Codex。"
echo ""
