/** Fixed-story reference implementation. Narration identity is supplied by the caller. */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
if (!process.argv[2]) throw new Error('Usage: node build-demo.mjs <prepared-demo-project>');
const out=path.resolve(process.argv[2]);
const timing=JSON.parse(fs.readFileSync(path.join(out,'assets/audio/timing.json'),'utf8'));
const R=timing.records,total=Math.ceil(timing.duration*30)/30;
const script=JSON.parse(fs.readFileSync(path.join(repo,'assets/examples/script.json'),'utf8'));
if (!(total > 0 && total <= 60) || !Array.isArray(R) || R.length!==10) throw new Error('Demo requires ten lines and duration <=60s');
for(let i=0;i<R.length;i++) {
 if(R[i].text!==script.lines[i].text || ![R[i].start,R[i].end,R[i].duration].every(Number.isFinite) || R[i].end<=R[i].start || (i && R[i].start<R[i-1].end)) throw new Error('Invalid demo line/timing '+i);
}
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const paper='#F8F1E3',ink='#292620';
const stroke=(d,fill='none',w=5)=>`<path d="${d}" fill="${fill}" stroke="${ink}" stroke-width="${w}" stroke-linecap="round" stroke-linejoin="round"/>`;
const svg=(w,h,inner)=>`<svg viewBox="0 0 ${w} ${h}" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">${inner}</svg>`;
const txt=(x,y,t,size=44,extra='')=>`<text x="${x}" y="${y}" font-size="${size}" ${extra}>${esc(t)}</text>`;
function pose(id,index,x,y,size){let col=index%3,row=Math.floor(index/3);return `<div id="${id}" class="pose" style="left:${x}px;top:${y}px;width:${size}px;height:${size*(index<3?.93:1)}px"><img src="assets/images/acting-sheet-v2.png" alt="原创下班小人表演姿势" style="width:${size*3}px;height:${size*2}px;left:${-col*size}px;top:${-row*size}px"></div>`;}
const floor=(top=1420)=>`<div class="floor" style="top:${top}px">${svg(1000,45,stroke('M10 20Q290 12 490 20T980 16','none',3)+stroke('M110 36L285 34M720 34L857 32','none',1.5))}</div>`;
function bubble(id,x,y,w,text){return `<div id="${id}" class="bubble" style="left:${x}px;top:${y}px;width:${w}px">${esc(text)}</div>`;}
function book(id,x,y,angle,label='',size=190){return `<div id="${id}" class="book" style="left:${x}px;top:${y}px;width:${size}px;height:${size*.70}px;transform:rotate(${angle}deg)">${svg(220,160,stroke('M14 23L179 9L207 128L38 149Z','#F8F1E3',5)+stroke('M24 23L44 134L200 115M32 31L172 19M49 127L191 109M54 139L195 121','none',2)+stroke('M55 50L154 40M57 56L158 46M71 91L150 83','none',1.3)+txt(57,87,label,30,id.startsWith('flood-')?'data-layout-allow-overlap':''))}</div>`;}
function doc(id,x=105,y=350,w=870,h=810,title='新邮件'){return `<div id="${id}" class="document" style="left:${x}px;top:${y}px;width:${w}px;height:${h}px"><div class="doc-top"><span>${title}</span><span>— ×</span></div><div class="subject">主题：今天的进度</div><div class="doc-body" id="${id}-body"><span id="${id}-text"></span><span id="${id}-cursor" class="cursor">│</span></div><div class="doc-foot" id="${id}-foot">草稿 · 0 字</div></div>`;}
function phone(id,x,y,w=255,h=460){return `<div id="${id}" class="phone" style="left:${x}px;top:${y}px;width:${w}px;height:${h}px"><div class="earpiece"></div><div class="phone-screen"><span class="phone-ai">AI</span><span class="phone-update">又更新了</span></div><div class="home-dot"></div></div>`;}
const css=`@font-face{font-family:Cartoon;src:url('assets/fonts/Chinese.ttf')}*{box-sizing:border-box} .world{position:absolute;inset:0;overflow:hidden;background:${paper}} .pose{position:absolute;overflow:hidden;transform-origin:50% 85%;mask-image:linear-gradient(to right,transparent,black 3%,black 97%,transparent),linear-gradient(to bottom,transparent,black 3%,black 97%,transparent);mask-composite:intersect}.pose img{position:absolute;max-width:none}svg text{font-family:Cartoon;fill:${ink};stroke:none}.book{position:absolute;transform-origin:50% 50%}.floor{position:absolute;left:40px;width:1000px;height:45px}.bubble{position:absolute;padding:26px 25px 30px;border:4px solid ${ink};border-radius:49% 44% 38% 40%;background:${paper};font:46px/1.25 Cartoon;text-align:center;transform-origin:25% 100%}.bubble:after{content:'';position:absolute;bottom:-20px;left:37px;width:29px;height:30px;background:${paper};border-right:4px solid ${ink};transform:skew(-35deg) rotate(19deg)}.document{position:absolute;background:#FFF9ED;border:5px solid ${ink};border-radius:12px 16px 10px 13px;transform-origin:50% 50%;font-family:Cartoon}.doc-top{height:94px;border-bottom:3px solid ${ink};padding:20px 28px;display:flex;justify-content:space-between;font-size:37px}.subject{padding:28px;font-size:34px;border-bottom:2px solid #C4BBAC}.doc-body{padding:55px 35px;font-size:46px;line-height:1.9;min-width:600px;white-space:pre-wrap}.cursor{display:inline-block;width:20px;color:#B5502C}.doc-foot{position:absolute;bottom:24px;left:32px;font-size:28px;color:#6F685C}.phone{position:absolute;border:7px solid ${ink};border-radius:29px;background:#ECE2D2;padding:38px 16px 36px;transform-origin:50% 85%;font-family:Cartoon}.earpiece{position:absolute;top:13px;left:40%;height:6px;width:21%;background:${ink};border-radius:7px}.phone-screen{height:100%;border:2px solid ${ink};display:flex;flex-direction:column;justify-content:center;align-items:center;background:#FFF8EB;gap:30px}.phone-ai{font-size:64px;border:4px solid ${ink};border-radius:14px;padding:10px}.phone-update{font-size:31px}.home-dot{position:absolute;bottom:9px;left:46%;width:17px;height:17px;border:2px solid ${ink};border-radius:50%}.tiny{position:absolute;font:35px/1.5 Cartoon;color:#756C5F}.accent{color:#B5502C}`;
let scenes=[];
function scene(id,start,end,body,anim){
  const duration=end-start;
  const html=`<!doctype html><html lang="zh"><head><meta charset="utf-8"></head><body><template><style>${css}#${id}{position:absolute;inset:0;width:1080px;height:1920px;overflow:hidden;background:${paper}}</style><div id="${id}" data-composition-id="${id}" data-width="1080" data-height="1920" data-duration="${duration.toFixed(6)}">${body}</div><script>const tl=gsap.timeline({paused:true});${anim}window.__timelines['${id}']=tl;</script></template></body></html>`;
  const initialHidden='#phone-shot,#phone-shocked,#shout-mouth,#warning,#shielding,#zero-mail,#blank-document,#actual-self,#yawn-shot,#leaving-shot';
  let refined=html.replace('</style>',`${initialHidden}{opacity:0}#shout-mouth{left:484px!important;top:310px!important}#tiny-witness{top:1150px!important;left:610px!important;width:380px!important;height:354px!important}#real-doc{height:800px!important}#rough-note{top:1260px!important;max-width:450px}.pose{mask-image:linear-gradient(to right,transparent,black 8%,black 92%,transparent),linear-gradient(to bottom,transparent,black 5%,black 96%,transparent)}</style>`).replace(/class="book"/g,'class="book" data-layout-allow-overflow');
  if(id==='phone-panic')refined=refined.replace("const tl=gsap.timeline({paused:true});","const tl=gsap.timeline({paused:true});gsap.set('#phone-shocked',{scaleX:-1});").replace("{scale:.02,opacity:0},{scale:1,opacity:1,duration:.3","{scale:.02,opacity:0,x:210,y:95},{scale:1,opacity:1,x:0,y:0,duration:.3");
  refined=refined.replace('</style>','#still-three{left:710px!important;top:150px!important;width:300px!important;font-size:40px;white-space:nowrap}</style>');
  fs.writeFileSync(path.join(out,'compositions',id+'.html'),refined); scenes.push({id,start,end,duration});
}
const A=R[2].start-.10,B=R[4].start-.12,C=R[5].start-.12,D=R[7].start-.12,E=R[8].start-.12;
const phoneShout=R[1].start+R[1].duration*.49;
scene('phone-panic',0,A,
`<div id="opener" class="world">${pose('tired-close',3,-340,-40,1760)}<div class="tiny" style="left:105px;top:190px">03:17 AM</div>${bubble('still-three',700,330,240,'还剩三根')}</div>
<div id="phone-shot" class="world">${pose('phone-calm',0,-25,410,1050)}${pose('phone-shocked',1,-90,470,1080)}${floor()}<div class="tiny" style="left:110px;top:250px">本来只想写封邮件</div>
<div id="shout-mouth" style="position:absolute;left:685px;top:520px;width:325px;height:540px;transform-origin:45% 95%">${svg(325,540,stroke('M116 500Q125 406 51 330Q-9 254 35 110Q53 8 157 22Q291 19 301 155Q330 313 224 378Q177 414 116 500','#D88755',6)+stroke('M60 131Q78 46 167 66Q266 67 267 176Q284 299 188 330Q99 363 65 258Z',ink,5)+stroke('M70 105Q155 43 255 112L250 156Q151 118 62 162Z','#FFF9ED',4)+stroke('M115 88L110 141M165 82L163 134M213 93L210 141','none',3)+stroke('M105 298Q155 233 227 298Q178 357 105 298','#D88755',3))}</div>${bubble('warning',110,300,720,'再不学，你就落后了！')}</div>`,
`tl.fromTo('#tired-close',{scale:1},{scale:1.05,duration:${R[1].start.toFixed(3)},ease:'none'},0);tl.fromTo('#still-three',{opacity:0,scale:.5},{opacity:1,scale:1,duration:.25,ease:'power3.out'},1.4);tl.set('#opener',{opacity:0},${R[1].start});tl.fromTo('#phone-shot',{opacity:0},{opacity:1,duration:.001},${R[1].start});tl.fromTo('#phone-shocked',{opacity:0},{opacity:1,duration:.001},${phoneShout+.14});tl.set('#phone-calm',{opacity:0},${phoneShout+.14});tl.fromTo('#shout-mouth',{scale:.02,opacity:0},{scale:1,opacity:1,duration:.3,ease:'back.out(1.15)'},${phoneShout});tl.fromTo('#warning',{scale:.1,opacity:0},{scale:1,opacity:1,duration:.25,ease:'power3.out'},${phoneShout+.17});tl.fromTo('#phone-shocked',{x:0,rotation:0},{x:-27,rotation:-3,duration:.18,ease:'power2.out',immediateRender:false},${phoneShout+.15});tl.to('#shout-mouth',{scaleY:.87,duration:.14,yoyo:true,repeat:9,ease:'sine.inOut'},${phoneShout+.35});`
);
let flood='';
for(let i=0;i<44;i++){let col=i%7,row=Math.floor(i/7);flood+=book('flood-'+i,-100+col*174+(row%2)*75,690+row*103-col*27,(i%5-2)*12,['入门','进阶','必学','新教程','速成',''][i%6],210+(i%3)*22);}
const floodAt=R[3].start-A+.18;
scene('book-flood',A,B,
`<div class="world">${pose('proud-one',2,-10,410,1110)}${pose('shielding',5,0,410,1100)}${floor()}${bubble('only-one',400,220,530,'就看一个。')}
<div id="all-books" style="position:absolute;inset:0;z-index:3">${flood}</div>
<div id="zero-mail" class="document" style="left:130px;top:270px;width:820px;height:310px;z-index:5;transform:rotate(-3deg)"><div class="doc-top"><span>邮件</span><span>草稿</span></div><div style="padding:34px;font:64px Cartoon">一个字<span class="accent">没动。</span></div></div></div>`,
`tl.fromTo('#shielding',{opacity:0},{opacity:1,duration:.001},${floodAt+.08});tl.set('#proud-one',{opacity:0},${floodAt+.08});tl.set('#only-one',{opacity:0},${floodAt});${Array.from({length:44},(_,i)=>`tl.fromTo('#flood-${i}',{x:1220,y:-570,rotation:45},{x:0,y:0,rotation:${(i%5-2)*12},duration:${(.68+(i%3)*.08).toFixed(2)},ease:'power2.out'},${(floodAt+i*.043).toFixed(3)});`).join('')}tl.to('#shielding',{y:125,rotation:-6,scaleY:.88,duration:.28,ease:'power2.in'},${floodAt+.68});tl.fromTo('#zero-mail',{opacity:0,y:-30,scale:.8},{opacity:1,y:0,scale:1,duration:.2,ease:'power3.out'},${R[3].start-A+R[3].duration*.62});`
);
const blankAt=(B===0?0: R[4].duration*.47);
scene('blank-page',B,C,
`<div id="blank-face" class="world">${pose('blank-eyes',3,-465,-210,1910)}${bubble('not-ai',650,1200,290,'不是怕它')}</div><div id="blank-document" class="world">${doc('blank-doc',80,285,920,1050)}<div class="tiny" style="left:165px;top:1410px">光标已经替我眨了半天眼。</div></div>`,
`tl.fromTo('#blank-eyes',{scale:1},{scale:1.05,duration:${blankAt},ease:'none'},0);tl.set('#blank-face',{opacity:0},${blankAt});tl.fromTo('#blank-document',{opacity:0},{opacity:1,duration:.001},${blankAt});tl.fromTo('#blank-doc-cursor',{opacity:1},{opacity:0,duration:.01,repeat:12,repeatDelay:.35,yoyo:true,ease:'none'},${blankAt});`
);
const realAt=R[5].duration*.55;
scene('recognition',C,D,
`<div id="learning-self" class="world">${pose('learning-proud',2,15,400,1080)}${book('one-book',100,1190,-15,'已收藏',235)}${bubble('busy',280,245,620,'我可太努力了。')}</div><div id="actual-self" class="world">${doc('small-doc',120,240,840,485)}${pose('actual-tired',3,35,760,1020)}<div id="excuse" class="tiny" style="left:510px;top:720px;transform:rotate(4deg)">（今天也没开始）</div></div>`,
`tl.to('#learning-proud',{rotation:-2,scale:1.015,duration:.25,ease:'power2.out'},.35);tl.set('#learning-self',{opacity:0},${realAt});tl.fromTo('#actual-self',{opacity:0},{opacity:1,duration:.001},${realAt});tl.fromTo('#excuse',{opacity:0},{opacity:1,duration:.15},${R[6].start-C+.45});tl.fromTo('#small-doc-cursor',{opacity:1},{opacity:0,duration:.01,repeat:16,repeatDelay:.35,yoyo:true,ease:'none'},${realAt});tl.to('#actual-tired',{y:20,scaleY:.975,duration:.6,ease:'power2.out'},${R[6].start-C+.25});`
);
const seq=[{t:0,text:''},{t:1.1,text:'你'},{t:1.24,text:'你好，'},{t:1.85,text:'你好，\n我先'},{t:2.03,text:'你好，\n我先写两行。'},{t:3.45,text:'你好，\n我先写个初稿。'},{t:4.05,text:'你好，\n我先写个初稿。'}];
scene('two-lines',D,E,
`<div class="world">${doc('real-doc',75,300,930,800)}${pose('tiny-witness',0,610,1150,380)}<div id="rough-note" class="tiny accent" style="left:130px;top:1260px;transform:rotate(-4deg)">不漂亮，但不是零。</div></div>`,
`const states=${JSON.stringify(seq)};const typeDriver={t:0};tl.to(typeDriver,{t:${E-D},duration:${E-D},ease:'none',onUpdate:()=>{let text='';for(let i=states.length-1;i>=0;i--){if(typeDriver.t>=states[i].t){text=states[i].text;break;}}document.getElementById('real-doc-text').textContent=text;document.getElementById('real-doc-foot').textContent='草稿 · '+text.replace(/\\s/g,'').length+' 字';}},0);tl.fromTo('#real-doc-cursor',{opacity:1},{opacity:0,duration:.01,repeat:16,repeatDelay:.35,yoyo:true,ease:'none'},0);tl.fromTo('#rough-note',{opacity:0},{opacity:1,duration:.2},${Math.min(4,E-D-1)});`
);
const endYawn=R[8].duration*.45;
scene('clock-out',E,total,
`<div id="update-shot" class="world">${pose('unimpressed',3,-40,430,1050)}${phone('last-phone',735,265,235,395)}${bubble('last-ping',140,200,510,'又更新了！')}</div><div id="yawn-shot" class="world">${pose('huge-yawn',4,-220,180,1420)}${bubble('you-busy',660,1020,270,'你忙。')}</div><div id="leaving-shot" class="world">${pose('leave-boy',4,35,430,1100)}${floor()}<div id="off-duty" style="position:absolute;left:155px;top:245px;font:77px Cartoon;transform:rotate(-5deg);color:${ink}">我先下班了。</div><div class="tiny" style="left:660px;top:1440px">明天再说。</div></div>`,
`tl.fromTo('#last-phone',{rotation:-4},{rotation:4,duration:.07,repeat:5,yoyo:true,ease:'none'},.16);tl.set('#update-shot',{opacity:0},${endYawn});tl.fromTo('#yawn-shot',{opacity:0},{opacity:1,duration:.001},${endYawn});tl.to('#huge-yawn',{rotation:2,scale:1.025,duration:.7,ease:'sine.inOut'},${endYawn+.1});tl.fromTo('#you-busy',{opacity:0,scale:.4},{opacity:1,scale:1,duration:.2,ease:'power3.out'},${endYawn+.15});tl.set('#yawn-shot',{opacity:0},${R[9].start-E});tl.fromTo('#leaving-shot',{opacity:0},{opacity:1,duration:.001},${R[9].start-E});tl.to('#leave-boy',{x:36,y:-3,rotation:1,duration:.4,ease:'power2.out'},${R[9].start-E+.2});`
);

const sfxManifest=path.join(out,'assets/sfx/manifest.json');
const soundMeta=fs.existsSync(sfxManifest)?JSON.parse(fs.readFileSync(sfxManifest,'utf8')):{};
fs.mkdirSync(path.join(out,'assets/sfx'),{recursive:true});
const plannedCues=[['notification',phoneShout-.08,.12],['whoosh-short',R[3].start+.15,.18],['pop',R[3].start+1.05,.14],['key-press',D+1.1,.25],['key-press',D+1.25,.25],['key-press',D+1.85,.25],['key-press',D+2.03,.25],['key-press',D+3.45,.25],['notification',E+.08,.10],['click-soft',R[9].start,.2]];
const cues=plannedCues.filter(([name])=>soundMeta[name] && Number.isFinite(soundMeta[name].duration) && soundMeta[name].duration>0);
if(cues.length!==plannedCues.length) console.warn('Some SFX are not supplied: see plannedCues in scenes.json; not a full sound-design reproduction.');
for(const [name] of cues) {
 const f=soundMeta[name].file;
 if(typeof f!=='string' || path.basename(f)!==f || !fs.existsSync(path.join(out,'assets/sfx',f))) throw new Error('Missing or unsafe SFX file '+name);
}
const captions=timing.captions.map((c,i)=>`<div id="cap-${i}" class="clip caption" data-start="${c.startMs/1000}" data-duration="${(c.endMs-c.startMs)/1000}" data-track-index="8">${esc(c.text)}</div>`).join('\n');
const root=`<!doctype html><html lang="zh"><head><meta charset="utf-8"><title>下班小人 · 先写两行</title><script src="assets/gsap.min.js"></script><style>@font-face{font-family:Cartoon;src:url('assets/fonts/Chinese.ttf')}*{box-sizing:border-box}html,body{margin:0;width:1080px;height:1920px;overflow:hidden;background:${paper}}.clip{position:absolute;inset:0;width:1080px;height:1920px}.caption{top:1580px;left:85px;width:910px;height:125px;padding:14px 18px;font:49px/1.4 Cartoon;text-align:center;color:${ink};background:${paper};border-radius:15px;z-index:20}.brand{position:absolute;left:100px;bottom:85px;font:27px Cartoon;letter-spacing:3px;color:#8A8070;z-index:22}</style></head><body><div id="main" data-composition-id="main" data-width="1080" data-height="1920" data-duration="${total}">${scenes.map(s=>`<div class="clip" data-composition-id="${s.id}" data-composition-src="compositions/${s.id}.html" data-start="${s.start}" data-duration="${s.duration}" data-track-index="1" data-width="1080" data-height="1920"></div>`).join('\n')}${captions}<audio id="narration" src="assets/audio/voice.wav" data-start="0" data-duration="${timing.duration}" data-track-index="10" data-volume="1"></audio>${cues.map(([n,t,v],i)=>`<audio id="sfx-${i}" src="assets/sfx/${soundMeta[n].file}" data-start="${t}" data-duration="${soundMeta[n].duration}" data-track-index="${11+i%3}" data-volume="${v}" data-audio-group="sfx"></audio>`).join('\n')}</div><script>window.__timelines=window.__timelines||{};window.__timelines['main']=gsap.timeline({paused:true});</script></body></html>`;
fs.writeFileSync(path.join(out,'index.html'),root.replaceAll('<div class="clip" data-composition-id="','<div class="clip" id="scene-host-').replace(/id="scene-host-([^"]+)" data-composition-src=/g,'id="scene-host-$1" data-composition-id="$1" data-composition-src='));
fs.writeFileSync(path.join(out,'scenes.json'),JSON.stringify({total,scenes,cues,plannedCues,captionTiming:timing.captionTiming},null,2));
console.log(JSON.stringify({duration:total,scenes:scenes.length,voice:timing.voiceIdentity}));
